version: "3"
tasks:
  train:
    desc: Train FrozenLake with DQN (hyperparameter-tuned)
    cmds:
      - |
        python -m rl_for_dummies.dqn_jax \
        --env-id "FrozenLake-v1" \
        --learning-rate 0.0005 \
        --buffer-size 100 \
        --gamma 0.99 \
        --tau 0.92 \
        --target-network-frequency 4000 \
        --batch-size 128 \
        --start-e 0.5 \
        --end-e 0.01 \
        --exploration-fraction 0.2 \
        --learning-starts 0 \
        --train-frequency 10 \
        --env-kwargs '{"is_slippery": false}'

  train_reinforce:
    desc: Train FrozenLake with REINFORCE (simple)
    cmds:
      - |
        python -m rl_for_dummies.reinforce_jax \
        --env-id "FrozenLake-v1" \
        --total-timesteps 15000 \
        --env-kwargs '{"is_slippery": false}'

  train_dqn_simple:
    desc: Train FrozenLake with DQN (simple)
    cmds:
      - |
        python -m rl_for_dummies.dqn_simple_jax \
        --env-id "FrozenLake-v1" \
        --exploration-fraction 0.1 \
        --total-timesteps 15000 \
        --env-kwargs '{"is_slippery": false}'

  train_dqn_pushworld:
    desc: Train PushWorld with DQN (simple)
    cmds:
      - |
        python -m rl_for_dummies.dqn_simple_jax \
        --env-id "PushWorld-v0" \
        --exploration-fraction 0.4 \
        --start-e 0.4 \
        --total-timesteps 100000 \
        --network "SimplePushWorldQNetwork" \
        --visualize-frequency 100

  train_meta_a2c_pushworld:
    desc: Train PushWorld with Meta A2C (simple)
    cmds:
      - |
        python -m rl_for_dummies.pushworld.meta_a2c_pushworld
